language: c

compiler: gcc

env:
    global:
        - USE_CCACHE=1
    matrix:
        - TARGET=i586
        - TARGET=iamcu
        - TARGET=nios2
        - TARGET=arm
        - TARGET=riscv32
        - TARGET=mips

build:
    cache: true
    cache_dir_list:
        - ${SHIPPABLE_BUILD_DIR}/ccache
        - ${SHIPPABLE_BUILD_DIR}/sources
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.3
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - ccache -s
      - sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential
      - sudo apt-get install -y libreadline-dev gperf flex bison libncurses5-dev texinfo help2man
      - unset CC
      - ./go.sh ${TARGET}
      - ccache -s
