# SPDX-License-Identifier: Apache-2.0

include(${CMAKE_CURRENT_LIST_DIR}/arc-cross-compile.cmake)

set(__HELPER_CC ${CROSS_COMPILE_TARGET_${ARCH}})
set(ARCMWDT_HELPER_PATH ${ZEPHYR_SDK_INSTALL_DIR}/${__HELPER_CC}/bin/)

set(ARCMWDT_HELPER_DTS_PREPROCESSOR_BIN ${__HELPER_CC}-gcc)
set(ARCMWDT_HELPER_OBJCOPY_BIN ${__HELPER_CC}-objcopy)

set(ARCMWDT_HELPER_DTS_PREPROCESSOR ${ARCMWDT_HELPER_PATH}/${ARCMWDT_HELPER_DTS_PREPROCESSOR_BIN})
set(ARCMWDT_HELPER_OBJCOPY ${ARCMWDT_HELPER_PATH}/${ARCMWDT_HELPER_OBJCOPY_BIN})
